
CREATE TABLE asset(
    id bigserial primary key not null,
    from_currency varchar not null,
    to_currency varchar not null,
    data json,
    is_acquired bool DEFAULT false,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone
);

INSERT INTO asset(from_currency, to_currency, created_at, updated_at) VALUES 
('BTC', 'USD', now(), now()),
('BTC', 'EUR', now(), now()),
('BTC', 'GBP', now(), now()),
('BTC', 'JPY', now(), now()),
('BTC', 'RUR', now(), now()),
('XRP', 'USD', now(), now()),
('XRP', 'EUR', now(), now()),
('XRP', 'GBP', now(), now()),
('XRP', 'JPY', now(), now()),
('XRP', 'RUR', now(), now()),
('ETH', 'USD', now(), now()),
('ETH', 'EUR', now(), now()),
('ETH', 'GBP', now(), now()),
('ETH', 'JPY', now(), now()),
('ETH', 'RUR', now(), now()),
('BCH', 'USD', now(), now()),
('BCH', 'EUR', now(), now()),
('BCH', 'GBP', now(), now()),
('BCH', 'JPY', now(), now()),
('BCH', 'RUR', now(), now()),
('EOS', 'USD', now(), now()),
('EOS', 'EUR', now(), now()),
('EOS', 'GBP', now(), now()),
('EOS', 'JPY', now(), now()),
('EOS', 'RUR', now(), now()),
('LTC', 'USD', now(), now()),
('LTC', 'EUR', now(), now()),
('LTC', 'GBP', now(), now()),
('LTC', 'JPY', now(), now()),
('LTC', 'RUR', now(), now()),
('XMR', 'USD', now(), now()),
('XMR', 'EUR', now(), now()),
('XMR', 'GBP', now(), now()),
('XMR', 'JPY', now(), now()),
('XMR', 'RUR', now(), now()),
('DASH', 'USD', now(), now()),
('DASH', 'EUR', now(), now()),
('DASH', 'GBP', now(), now()),
('DASH', 'JPY', now(), now()),
('DASH', 'RUR', now(), now());